### ISSUE TITLE
Config menu nesting and position (user-control, convenience) 

### ISSUE THREAD

**Issue by clojens** [tzyganu/UMC1.9#74]
Today when using UMC I noticed while you do (and great/easy) allow for a plugin to be nested anywhere in the adminhtml top menu bar tree, this is not available to the configuration part. One difference is probably instead of submenu, you have the expandable option tabs which can be ordered too. Although also easily done via XML I guess, that might be said for system.xml/adminhtml.xml menu bar as well (pretty much everything in Magento can be done in PHP or XML as you know :) so I'm not sure if you hadn't thought about it, it was/is harder than it looks, or whatever... thought I'd mention/ask about it though. Not so much high priority either I could figure so use as you please :)

More precise, I talk about the top two on the screen shot have the link below them, the row below those `-> Configuration` don't

![image](https://cloud.githubusercontent.com/assets/3727933/5587475/3c602616-90ec-11e4-9f09-44d20682c78d.png)

**Comment by tzyganu** [comment]
@clojens Sorry for the late response. 
I have thought of that and decided not to do it. Mostly because it takes some work and the value it adds is not that big.  
Since you can have more than one entity in your module and all of them can have configuration settings, all of the entity settings should be placed under the same section. Adding them to the catalog section for example will probably cause them to be scattered all around the place. Having them in one single place gives a feeling of consistency.  

And, as I said before, the UMC does not deliver "ready to ship" extensions. It's just a way to kickstart  your extension.  
If you want you can move the configuration elements anywhere just by changing the system.xml file and all the constants that use the paths in the configuration.   

I have no plans on implementing this.
