### ISSUE TITLE
Relationship "is parent of" include tab of children on parent?

### ISSUE THREAD

**Issue by pljspahn** [tzyganu/UMC1.9#80]
When we use "is parent of" relationships, the child gets a select field where they can choose from a list of parents. If we then go to edit the parent, there is no left tab that contains a list of children entities. 

Was this not included as part of the relationship for a reason?

**Comment by tzyganu** [comment]
@pljspahn This is not included because it's not mandatory.
If you want to see the child entities for a specific parent entity, use the main grid and filter by parent entity. If you want to bulk assign child entities to a parent entity, use the main grid mass action.  
There is no plan to implement this in the next releases.

**Comment by pljspahn** [comment]
Ah! Mass action on the grid! I missed that.
