### ISSUE TITLE
Display linked products in widget

### ISSUE THREAD

**Issue by j4cq** [tzyganu/UMC1.9#94]
Is it possible to display the linked products in the widget view? I have not had any luck implementing this so any pointers would be appreciated

**Comment by tzyganu** [comment]
@j4cq The code you need to list the products associated to an entity can be found in the class `{{Namespace}}_{{Module}}_Block_{{Entity}}_Catalog_Product_List` (replace the placeholders with your values.).  
And here is a tutorial on [how to create a widget](http://code.tutsplus.com/tutorials/custom-widget-development-in-magento--cms-23015).  
You just have to put them together.  

I will close this for now, since it's not in the scope of the extension.
