### ISSUE TITLE
Image attribute naming convention?

### ISSUE THREAD

**Issue by modernminds** [tzyganu/UMC1.9#95]
See issue: https://github.com/tzyganu/UMC1.9/issues/89

I experience the same error where the image wont display. Resulting HTML: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEU......." />

Nevertheless, it seems to work for some of the image attributes that I use for the same plugin. I think there might be a problem with the naming convention of the plugin.

When you use an attribute called 'question_image_1' this seems not to work. I think it might be due to the _1, since my image attribute called 'quiz_image' is working fine.

There is also another bug with this naming convention in the view.phtml file. The generated view.phtml used $_quiz->getQuestionImage1() whereas it should be $_quiz->getQuestionImage_1(). This one I could fix myself, but the other issue I cannot debug.

**Comment by tzyganu** [comment]
the naming convention for the generated extension follows the naming convention of magento in general.  
It is never a good idea to use _1 or _2 at the end of an attribute /column name.  
The reason?...exactly what you said. you cannot use the magic getters and setter.  
I will close this for now since is not an extension related issue. This is how magento works.
